id: A74E5A605
base_file: f3791.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 19:59:28.185931
  last_modified_at: 2022-06-05 19:59:28.185938
